### ISSUE TITLE
Notification Permission not setting for Xcode 11.1

### ISSUE THREAD

**Issue by billburgess** [wix/AppleSimulatorUtils#66] opened 2019-11-07 16:51 UTC
**Description**
My local builds are no longer setting the Notification permission for iOS 13.1 devices. I haven't updated anything in my project recently. It may be related to a recent update as I recently upgraded from 0.7.4 to 0.7.6.

The issue seems isolated to runtime 13.1. The same suite of tests and commands works perfectly on iOS 12.2.

**Steps to Reproduce**
I'm running my test suite with a device I create specific for the test run. Using iOS 13.1 runtime. Once the device is created, I boot the device and wait 30 sec. Then run applesimutils on the new device setting notifications, location, and contacts.

`applesimutils --byName "iOS13TestDevice" --bundle "simpleinout" --setPermissions "notifications=YES, location=always, contacts=YES" || sleep 30`

**Expected Behavior**
All previous versions would set this permission and the system prompts would never show during the test run.

**Environment**
 - macOS version: 10.15.1
 - Xcode version: 11.1 (direct install)

**Comment by LeoNatan** [comment] 2019-11-15 02:02
Thanks, I will take a look soon.

**Comment by billburgess** [comment] 2019-12-16 14:59
This is still an issue on Xcode 11.3. Any updates on getting this to work?

**Comment by LeoNatan** [comment] 2019-12-16 15:59
I will look at it probably tomorrow.

**Comment by LeoNatan** [comment] 2019-12-17 08:58
Can't reproduce this on the default 13.2.2 runtime. Downloading the 13.1 runtime now to check.

**Comment by LeoNatan** [comment] 2019-12-17 09:50
@billburgess I can't reproduce with the 13.1 runtime either.

This is the code I am using in my sample app:

```
UNUserNotificationCenter* center = [UNUserNotificationCenter currentNotificationCenter];
[center requestAuthorizationWithOptions: UNAuthorizationOptionAlert | UNAuthorizationOptionSound completionHandler:^(BOOL granted, NSError * _Nullable error) {
	NSLog(@"Notifications: %@", granted ? @"<granted>" : @"<not granted>");
}];
```

The output is correctly "<granted>".

**Comment by billburgess** [comment] 2019-12-18 18:13
I can't seem to recreate this issue in Xcode 11.2 (iOS 13.3). I'm not sure if this was actually an issue or not. I'll close this issue for now and I'll keep an eye on it. Sorry for the trouble.

**Comment by LeoNatan** [comment] 2019-12-18 18:19
Thank you!

**Comment by LeoNatan** [comment] 2020-01-15 12:14
We're seeing this sporadically as well.
From investigation, it seems that SpringBoard is responsible for writing to the VersionedSectionInfo.plist file. I suspect there is a condition where SpringBoard flushes its own cached file contents just after using applesimutils, which invalidates the change. Investigating.

**Comment by LeoNatan** [comment] 2020-01-29 14:17
Closing this issue in favor of the other one.

**Closed by LeoNatan** 2020-01-29 14:17 UTC
Labels: bug
